### ISSUE TITLE
Harmonization of license statements

### ISSUE THREAD

**Issue by FriedrichFroebel** [hsnr-gamera/gamera-4#70]
The code currently has different license statements, which should be unified to make everything more clear:

* General GPL with reference to *LICENSE* file: https://github.com/hsnr-gamera/gamera-4/blob/8bbda5ddae5abcde57019c3e7af0616e1c19c854/README.md?plain=1#L30
* The GPL-2.0 license file itself at https://github.com/hsnr-gamera/gamera-4/blob/master/LICENSE
* The `GPL-2.0-only` statement in https://github.com/hsnr-gamera/gamera-4/blob/8bbda5ddae5abcde57019c3e7af0616e1c19c854/setup.py#L196
* The `GPL-2.0-only` trove classifier in https://github.com/hsnr-gamera/gamera-4/blob/8bbda5ddae5abcde57019c3e7af0616e1c19c854/setup.py#L223
* The `GPL-2.0-or-later` header in most of the source files: https://github.com/hsnr-gamera/gamera-4/blob/8bbda5ddae5abcde57019c3e7af0616e1c19c854/setup.py#L7-L10

The above does not include license statements for the third-party modules, which might have different licenses and sometimes even strange copyright statements which do not appear to really match the actual general license (example: `src/eodev` provides a mix of different LGPL versions, while the actual license for the `eodev` module is considered `LGPL-2.1-only`).

**Comment by cdalitz** [comment]
Thanks for spotting this. I have harmonized this to v2 or later and have changed the trove classification to plain GPL.

Concerning the third party LGPL library, this should not be an issue because the LGPL explicitly allows for embedding the library into a GPL project. Actually this is the whole point of the *L*GPL: that the software using the library can use a different license than the LGPL.

**Comment by FriedrichFroebel** [comment]
No worries, I am aware that this does not necessarily impose an issue for Gamera, but just marks an inconsistency in the third-party dependencies itself.
